name: RAFT-RS CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Check formatting
      run: cargo fmt -- --check
  
    - name: Check Unused Dependencies
      run: | 
        cargo install cargo-machete
        cargo machete
  
    - name: Check Linting
      run: cargo clippy -- -D warnings

    - name: Build project
      run: cargo build
